### ISSUE TITLE
Two character long format strings are always printed literaly

### ISSUE THREAD

**Issue by ghost** [nonpop/xkblayout-state#2]
Calling something like `xkblayout-state print "%s"` will not work as expected (printing the current layout symbol) with the latest master. I think the reason is the change on row 62 in `wrapper.cpp` brought in commit 2602e1710fd77edd0d4839851c0d598dac50e8a7. It changes the check from `i < format.length()-1` to `i < format.length()-2` which will always be false for 2 characters long strings.

**Comment by nonpop** [comment]
Seems like an odd changed indeed. Does everything work properly if you change it back to 1? I cannot try it myself at the moment (something else is broken, too, causing an immediate segfault on my machine, and I don't have time to check it).

**Comment by ghost** [comment]
Changing it back to 1 does make it work. It hasn't shown any problems for now either.
