### ISSUE TITLE
std::logic_error on layout toggle

### ISSUE THREAD

**Issue by victorz** [nonpop/xkblayout-state#5]
I have two layouts, English and Swedish. I have the following in `~/.xprofile`:

```bash
# set English and Swedish as the two available layouts
setxkbmap -layout us,se
# reset options
setxkbmap -option
# make caps lock a 2nd ctrl
setxkbmap -option ctrl:nocaps
# alt+shift toggles layout
setxkbmap -option grp:alt_shift_toggle
```

Now, if I run xkblayout-state after each time I press Alt-Shift, it goes like this:

```bash
$ ./xkblayout-state print $'%n\n'
English
$ ./xkblayout-state print $'%n\n' # after toggling layouts
Swedish
$ ./xkblayout-state print $'%n\n' # after toggling layouts again
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
zsh: abort (core dumped)  ./xkblayout-state print $'%n\n'
$ ./xkblayout-state print $'%n\n' # after toggling layouts yet again
English
```

I'm unsure whether this is a problem with xkblayout-state or whether there's something weird going on with my setup, but it seems like there's three states, two of which are declared in my .xprofile, and a third one which seems to fail hard in xkblayout-state. If this isn't a problem with xkblayout-state, maybe you know some information about what's causing it with my setup above. Thanks for any information!

**Comment by nonpop** [comment]
I don't really understand much about the underlying system; I just made a little wrapper around an existing library... :p
